### ISSUE TITLE
exe2m  problem

### ISSUE THREAD

**Issue by excllent123** [ash255/matlab_exe_unpack#1]
Hi  ash255,
   
      Can  you share a exe demo  for debug?

Thanks

**Comment by ash255** [comment]
请访问https://github.com/ash255/exe2m/releases/tag/v1.0

**Comment by excllent123** [comment]
[exe2m.zip](https://github.com/ash255/exe2m/files/7902709/exe2m.zip

可以帮忙Debug问题吗，测试了下问题出在初始化过程

**Comment by ash255** [comment]
matlab运行库更新了，一些密钥变了，周末给你调好

**Comment by ash255** [comment]
我怀疑版本问题，我使用的是2018a
能否上传一下以下文件，用于复现你的环境
MATLAB\R2018a\bin\win64\mclmcr.dll
MATLAB\R2018a\bin\win64\ctfrtcrypto.dll

**Comment by excllent123** [comment]
[Uploading Matlab_dll.zip…]()
matlab版本为2020B,对应mclmcr/ctfrtcrypto  见附件，感谢！

**Comment by ash255** [comment]
![Desktop](https://user-images.githubusercontent.com/38106911/150994482-00f38b52-15e2-4ed0-a12f-ac7c319469a5.jpg)

**Comment by excllent123** [comment]
这边看不到截图 = =

**Comment by ash255** [comment]
那不是图片，而是一个文件，只是我以图片的形式上传，你在Desktop上右键另存为
