### ISSUE TITLE
神仙项目

### ISSUE THREAD

**Issue by tedcriss** [ash255/matlab_exe_unpack#2]
这个项目绝对是神仙宝藏项目，成功将编译的exe解码为可读的m文件，解决了困扰我好久的大问题，谢谢分享！！！！！！！！
提一个小建议，如果能将release中exe程序的命令行窗口默认编码改为unicode就更好了，gbk编码在英文系统下乱码，需要换中文系统电脑才能看懂，哈哈，自己编译也能解决这个问题。

**Comment by Dimple-Shang** [comment]
您好！想使用您的这个EXE程序解密文件  可以发一份给我吗？十分感谢!
1258183297@qq.com

**Comment by ash255** [comment]
> 您好！想使用您的这个EXE程序解密文件 可以发一份给我吗？十分感谢! [1258183297@qq.com](mailto:1258183297@qq.com)

有release可以下载的
https://github.com/ash255/matlab_exe_unpack/releases/tag/v1.1

**Comment by Dimple-Shang** [comment]
您好！出现报错。  此应用无法在你的电脑上运行，若要找到适用你的电脑版本，请咨询软件发布者。   不知您能否给一个 .bat 批处理文件直接运行 不知这样是否可以。 期待您的回复，谢谢！

> > 您好！想解密您的这个EXE程序文件可以发一份给我吗？十分感谢！[1258183297@qq.com](mailto:1258183297@qq.com)
> 
> 有release可以下载的 https://github.com/ash255/matlab_exe_unpack/releases/tag/v1.1

您好！出现报错。  此应用无法在你的电脑上运行，若要找到适用你的电脑版本，请咨询软件发布者。   不知您能否给一个 .bat 批处理文件直接运行 不知这样是否可以。 期待您的回复，谢谢！

**Comment by ash255** [comment]
> 您好！出现报错。 此应用无法在你的电脑上运行，若要找到适用你的电脑版本，请咨询软件发布者。 不知您能否给一个 .bat 批处理文件直接运行 不知这样是否可以。 期待您的回复，谢谢！
> 
> > > 您好！想解密您的这个EXE程序文件可以发一份给我吗？十分感谢！[1258183297@qq.com](mailto:1258183297@qq.com)
> > 
> > 
> > 有release可以下载的 https://github.com/ash255/matlab_exe_unpack/releases/tag/v1.1
> 
> 您好！出现报错。 此应用无法在你的电脑上运行，若要找到适用你的电脑版本，请咨询软件发布者。 不知您能否给一个 .bat 批处理文件直接运行 不知这样是否可以。 期待您的回复，谢谢！

重新下载一下，用里面win32的版本，输入的exe放入input目录，运行startup.bat就行了，输出在outpu目录
