### ISSUE TITLE
matlab 2007a exe 解析错误

### ISSUE THREAD

**Issue by TonyTuT** [ash255/matlab_exe_unpack#4]
错误提示 [ERROR][dec_matlab_file_v1]:no key match for file_body_1
[ERROR][main]:no key match for file_body_1

**Comment by TonyTuT** [comment]
错误提示 [ERROR][dec_matlab_file_v1]:no key match for file_body_1
                [ERROR][main]:no key match for file_body_1

**Comment by TonyTuT** [comment]
另外，使用keyer也有些问题

**Comment by TonyTuT** [comment]
[matlab2007a - runtime 7.6.zip](https://github.com/ash255/matlab_exe_unpack/files/11458500/matlab2007a.-.runtime.7.6.zip)

**Comment by ash255** [comment]
我看了你发的压缩包，里面的helloworld.exe是一个压缩包，并不是一个有效的可执行程序
由matlab的MCC命令编译出来的exe文件内部存在用于解密的密钥（manifest.xml），helloworld.exe并不包含manifest.xml，故无法解密成功。
如果可以，请你提供出出现问题的文件。
